package com.github.recoleta.mixin.client;

import com.github.recoleta.config.MemoryConfig;
import net.minecraft.client.particle.ParticleEngine;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.Constant;
import org.spongepowered.asm.mixin.injection.ModifyConstant;

/**
 * Caps the per-render-style particle {@code EvictingQueue} from the
 * vanilla 16384 down to the user-configurable
 * {@link MemoryConfig#PARTICLE_PER_TYPE_CAP}.
 *
 * <p>The vanilla {@link ParticleEngine#tick()} method lazily creates a
 * Guava {@code EvictingQueue.create(16384)} for every render type the
 * client encounters. With ~12 render types in vanilla and ~50 with
 * common mods loaded, that translates into hundreds of thousands of
 * pre-allocated array slots even when no particles are visible.
 * Lowering the cap to {@code 4096} (default) reclaims tens of MB of
 * client heap with no perceptible visual difference outside of
 * worst-case redstone particle storms.</p>
 *
 * <p>The actual {@code EvictingQueue.create(int)} call lives inside an
 * anonymous lambda generated by {@code javac}. Lambda method names
 * ({@code lambda$tick$0}, {@code lambda$tick$1}, ...) are not stable
 * across recompiles, so this mixin enumerates the most likely names
 * and is declared with {@code require = 0, expect = 0} so that loader
 * never fails the game if a future Forge build renames them &mdash;
 * the cap is then silently inactive and the user receives the vanilla
 * behaviour.</p>
 */
@Mixin(ParticleEngine.class)
public abstract class ParticleEvictionLimitMixin {

    /**
     * Replaces the hard-coded {@code 16384} constant with the configured
     * cap.
     *
     * @param original the vanilla constant intercepted by mixin
     * @return the user-configured upper bound on per-style particle count
     */
    @ModifyConstant(
            method = {
                    "lambda$tick$0", "lambda$tick$1",
                    "lambda$tick$2", "lambda$tick$3",
                    "lambda$tick$4"
            },
            constant = @Constant(intValue = 16384),
            require = 0, expect = 0
    )
    private int recoleta$capParticleQueue(final int original) {
        final int cap = MemoryConfig.PARTICLE_PER_TYPE_CAP.get();
        return Math.min(original, cap);
    }
}

